// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDisposalSchedule) DeepCopyInto(out *PodDisposalSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDisposalSchedule.
func (in *PodDisposalSchedule) DeepCopy() *PodDisposalSchedule {
	if in == nil {
		return nil
	}
	out := new(PodDisposalSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodDisposalSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDisposalScheduleList) DeepCopyInto(out *PodDisposalScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodDisposalSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDisposalScheduleList.
func (in *PodDisposalScheduleList) DeepCopy() *PodDisposalScheduleList {
	if in == nil {
		return nil
	}
	out := new(PodDisposalScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodDisposalScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDisposalScheduleSpec) DeepCopyInto(out *PodDisposalScheduleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDisposalScheduleSpec.
func (in *PodDisposalScheduleSpec) DeepCopy() *PodDisposalScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(PodDisposalScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDisposalScheduleStatus) DeepCopyInto(out *PodDisposalScheduleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDisposalScheduleStatus.
func (in *PodDisposalScheduleStatus) DeepCopy() *PodDisposalScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(PodDisposalScheduleStatus)
	in.DeepCopyInto(out)
	return out
}
